#ifndef DEF
#define DEF(k, v)
#endif

DEF(CommonPort,             "\\__emu_model_common_port"             )
DEF(ChannelDependsOn,       "\\__emu_model_channel_depends_on"      )
DEF(ChannelDirection,       "\\__emu_model_channel_direction"       )
DEF(ChannelName,            "\\__emu_model_channel_name"            )
DEF(ChannelPayload,         "\\__emu_model_channel_payload"         )
DEF(ChannelReady,           "\\__emu_model_channel_ready"           )
DEF(ChannelValid,           "\\__emu_model_channel_valid"           )
DEF(DUTClock,               "\\__emu_dut_clk"                       )
DEF(DUTReset,               "\\__emu_dut_rst"                       )
DEF(ExternIntf,             "\\__emu_model_extern_intf"             )
DEF(ExternIntfAddrPages,    "\\__emu_model_extern_intf_addr_pages"  )
DEF(ExternIntfType,         "\\__emu_model_extern_intf_type"        )
DEF(ModelImp,               "\\__emu_model_imp"                     )
DEF(NoScanchain,            "\\__emu_no_scanchain"                  )
