EMU_TOP := emu_top
SIM_TOP := sim_top

EMU_SRCS += emu_top.v
EMU_SRCS += mips_cpu.v
SIM_SRCS += emu_top.v
SIM_SRCS += mips_cpu.v
SIM_SRCS += singlecycle_test.v

IVL_ARGS += -DINITMEM_FILE=\"initmem.txt\"

include ../../common.mk
